In [2]:
import torch

In [3]:
def activation(x):
    """ Sigmoid activation function 
    
        Arguments
        ---------
        x: torch.Tensor
    """
    return 1/(1+torch.exp(-x))

In [4]:
# Single layer nural network
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 5 random normal variables
features = torch.randn((1, 5))
print(features)
# True weights for our data, random normal variables again
weights = torch.randn_like(features)
print(weights)
# and a true bias term
bias = torch.randn((1, 1))
print(bias)

tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])
tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])
tensor([[0.3177]])


In [5]:
# Output of neural network using sum() method
print(activation(torch.sum(features*weights)+bias))

tensor([[0.1595]])


In [7]:
# Output of neural network using matrix multiplication
# Getting transpose of weights matrix
weights_transpose = weights.view((5, 1))
print(weights_transpose)
product = torch.mm(features, weights_transpose)
print(product)

tensor([[-0.8948],
        [-0.3556],
        [ 1.2324],
        [ 0.1382],
        [-1.6822]])
tensor([[-1.9796]])


In [8]:
output = activation(product+bias)
print(output)

tensor([[0.1595]])


In [10]:
# Next exercise - Muti layer neural network
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 3))

# Define the size of each layer in our network
n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units 
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

print(features)
print(W1)
print(W2)
print(B1)
print(B2)

tensor([[-0.1468,  0.7861,  0.9468]])
tensor([[-1.1143,  1.6908],
        [-0.8948, -0.3556],
        [ 1.2324,  0.1382]])
tensor([[-1.6822],
        [ 0.3177]])
tensor([[0.1328, 0.1373]])
tensor([[0.2405]])


In [14]:
output_l1 = activation(torch.mm(features, W1)+B1)
print(output_l1)
output_l2 = activation(torch.mm(output_l1, W2)+B2)
print(output_l2)

tensor([[0.6813, 0.4355]])
tensor([[0.3171]])


In [18]:
# Numpy to Torch and back - example from course
import numpy as np
a = np.random.rand(4,3)
print(a)
b = torch.from_numpy(a) # Numpy to torch
print(b)

print(b.numpy()) # Torch to Numpy


[[0.26286322 0.81161691 0.0484664 ]
 [0.62818601 0.71249655 0.18202186]
 [0.83316878 0.30597497 0.20916981]
 [0.57371888 0.3225026  0.31739586]]
tensor([[0.2629, 0.8116, 0.0485],
        [0.6282, 0.7125, 0.1820],
        [0.8332, 0.3060, 0.2092],
        [0.5737, 0.3225, 0.3174]], dtype=torch.float64)
[[0.26286322 0.81161691 0.0484664 ]
 [0.62818601 0.71249655 0.18202186]
 [0.83316878 0.30597497 0.20916981]
 [0.57371888 0.3225026  0.31739586]]


In [19]:
# Multiply PyTorch Tensor by 2, in place
print(b.mul_(2))
print(a)

tensor([[0.5257, 1.6232, 0.0969],
        [1.2564, 1.4250, 0.3640],
        [1.6663, 0.6119, 0.4183],
        [1.1474, 0.6450, 0.6348]], dtype=torch.float64)
[[0.52572644 1.62323382 0.0969328 ]
 [1.25637203 1.42499311 0.36404372]
 [1.66633757 0.61194993 0.41833962]
 [1.14743775 0.6450052  0.63479172]]
